-- Deduplicate realized outcomes generated by rerunning target_generator.py.
-- Keep the earliest row for each logical target.
DELETE FROM realized_outcomes
WHERE outcome_id NOT IN (
    SELECT MIN(outcome_id)
    FROM realized_outcomes
    GROUP BY asset_id, origin_time, horizon_seconds
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_realized_outcomes_logical
ON realized_outcomes(asset_id, origin_time, horizon_seconds);
