CREATE TABLE IF NOT EXISTS market_state_v002_snapshots (
    snapshot_id INTEGER PRIMARY KEY AUTOINCREMENT,
    asset_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    last_price REAL NOT NULL,
    atr_14_pct REAL,
    realized_vol_30m_pct REAL,
    realized_vol_60m_pct REAL,
    realized_vol_390m_pct REAL,
    trend_slope_30m_pct REAL,
    trend_slope_60m_pct REAL,
    trend_slope_390m_pct REAL,
    return_5m_pct REAL,
    return_15m_pct REAL,
    return_30m_pct REAL,
    return_60m_pct REAL,
    return_390m_pct REAL,
    relative_return_5m_market_pct REAL,
    relative_return_15m_market_pct REAL,
    relative_return_30m_market_pct REAL,
    relative_return_60m_market_pct REAL,
    relative_return_390m_market_pct REAL,
    relative_return_5m_sector_pct REAL,
    relative_return_15m_sector_pct REAL,
    relative_return_30m_sector_pct REAL,
    relative_return_60m_sector_pct REAL,
    relative_return_390m_sector_pct REAL,
    return_percentile_5m REAL,
    return_percentile_15m REAL,
    return_percentile_30m REAL,
    return_percentile_60m REAL,
    volatility_percentile_60m REAL,
    volume_percentile_60m REAL,
    market_return_5m_pct REAL,
    market_return_15m_pct REAL,
    market_return_30m_pct REAL,
    market_return_60m_pct REAL,
    market_return_390m_pct REAL,
    market_vol_ratio_30m_390m REAL,
    breadth_5m REAL,
    breadth_15m REAL,
    breadth_30m REAL,
    breadth_60m REAL,
    feature_version TEXT NOT NULL,
    sector TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(asset_id, timestamp, feature_version),
    FOREIGN KEY(asset_id) REFERENCES assets(asset_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_market_v002_asset_time ON market_state_v002_snapshots(asset_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_market_v002_time ON market_state_v002_snapshots(timestamp);
